### ISSUE TITLE
I can see your hashed passwords in sec.conf (Weechat)

### ISSUE THREAD

**Issue by danger89** [arortell/dotfiles#1]

**Comment by arortell** [comment]
Thank you. That's very old, so I am not concerned about it. But I had no idea it was there. I do appreciate you bringing it to my attention.

**Comment by danger89** [comment]
Sure no problem. It's hashed, but still. Also Freenode is down, RIP Freenode. 

Officially you should rewrite your whole git history to get really rid of the file, but maybe that is for the next time you really need to delete something in plain text ;) 

`git filter-branch --index-filter -f 'rm -f path/to/mysecretpassword.txt' -- --all`
